rdf(i1, name, firefox).
rdf(i1, class, rm).
rdf(i2, name, firefox).
rdf(i2, class, run).
rdf(i2, short, f).
rdf(i3, name, facebook).
rdf(i3, short, fb).
rdf(i3, class, web).
rdf(i4, name, google-maps).
rdf(i4, short, map).
rdf(i4, class, web).
